# version: "3.1"
networks:
  library_network:
    driver: bridge

services:
  library:
    build: .
    container_name: library
    ports:
      - ${PORT}:${PORT}
    networks:
      - library_network
    env_file:
      - .env
    environment:
      MYSQL_DATABASE_HOST: ${MYSQL_DATABASE_HOST}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    restart: always
    volumes:
      - ./src:/usr/src/app/src

  nginx:
    image: nginx:latest
    container_name: nginx-cont
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./certbot/www/:/var/www/certbot/:ro
    depends_on:
      - library
    networks:
      - library_network
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on: nginx-cont
    networks:
      - library_network
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  app:
