networks:
  library_network:
    driver: bridge

services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    restart: always
    ports:
      - 3307:${MYSQL_PORT}
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - myapp:/home/app
    networks:
      - library_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - library_network
    links:
      - mysql-db

volumes:
  myapp:
